repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff-format
    stages: [commit]
    language: system
    entry: poetry run ruff format . --config pyproject.toml
    types: [python]

  - id: ruff
    name: ruff-check
    stages: [commit]
    language: system
    entry: poetry run ruff check hooks --fix --config pyproject.toml
    types: [python]
    exclude: setup.py

  - id: pytest
    name: pytest
    stages: [commit, push]
    language: system
    entry: poetry run pytest --cov
    types: [python]
    pass_filenames: false

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
    - id: mypy
      args: ['--config-file', 'pyproject.toml']
      exclude: '\{\{cookiecutter.package_name\}\}'
