name: Test Cookiecutter

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]

    name: Python ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5

      - name: Install dependencies with poetry
        run: poetry install

      - run: poetry run black --check hooks
      - run: poetry run ruff hooks
      - run: poetry run mypy

      - name: Configure git
        run: |
          git config --global user.email "default@example.com"
          git config --global user.name "Default Name"

      - name: Run cookiecutter
        run: poetry run cookiecutter . --no-input --config-file template_config.yml
