name: Test Poetry Cookiecutter

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    name: Python ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8

      - name: Install dependencies with poetry
        run: poetry install

      - run: poetry run ruff format hooks --check
      - run: poetry run ruff check hooks
      - run: poetry run mypy
      - run: poetry run pytest --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


      - name: Configure git
        run: |
          git config --global user.email "default@example.com"
          git config --global user.name "Default Name"
          git config --global init.defaultBranch master

      - name: Run cookiecutter
        run: poetry run cookiecutter . --no-input --config-file template_config.yml

      - name: Run pre-commit
        run: cd poetry_project && poetry install && poetry run pre-commit run --all-files
